### ISSUE TITLE
General Todo List

### ISSUE THREAD

**Issue by Shoeboxam** [SkytechWorld/Xielo_Android#1]
- [ ] Avatars
- [ ] Bypass login screen when logged in
- [ ] Popup menu for user pins
- [ ] Retrieve user info from firebase database
